### PR TITLE
Command order

### PR DESCRIPTION
**Pull request by richardssam**
There are a couple of places where we have been getting the list of arguments out of order, which breaks some of the tests.

What doesnt help is that the OTIO metadata dictionary is not ordered, so I'm now having to stash the command string, although thats not necessarily a bad thing.

### CODE REVIEW

**Comment by jminor** [comment]
OTIO's JSON writer is supposed to sort the keys to facilitate comparison. Is that not working as expected?

**Comment by richardssam** [comment]
What I'm seeing is that I put a ordered dictionary into the metadata node, but its re-ordered (possibly alphabetically) when it comes out.

**Comment by jminor** [comment]
Yes, in memory that dictionary is backed by a C++ `std::map<std::string, any>` which is unordered. On disk (as JSON) it should be sorted alphabetically.

If you need to preserve ordering, can you use an array instead of a dictionary?

**Comment by apetrynet** [comment]
Ah! I was under the impression that the order was garbled and different each time.

So, when you say sort @jminor, you mean an actual sort of type a-z?

**Comment by richardssam** [comment]
We can definitely work around it, its not critical that it be a dictionary, we are just getting spoilt by the python ordered dictionaries ;)

**Pull request merged**
